$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base.mk)
PRODUCT_NAME := omni_RCT6077W2
PRODUCT_DEVICE := RCT6077W2
PRODUCT_BRAND := RCA
PRODUCT_MANUFACTURER := Foxconn
PRODUCT_MODEL := RCT6077W2
